server:
  port: 8002

spring:
  application:
    name: service-consumer

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/
feign:
  hystrix:
    enabled:true
# 使用Hystrix Metrics Stream必备 
 management:
   endpoints: 
     web:
      exposure: 
        include: hystrix.stream   

